---
title: "Moral Foundations Questionnaire 2.0, Research Question 2"
output: html_document
---

```{r include = F}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(ggpubr)
library(lsa)
library(purrr)
library(lmerTest)

```

```{r include = F}

# load data
df <- read_csv("human_mfq_responses.csv")

names(df)[names(df) == "Response"] <- "human_response"

names(df)[names(df) == "Item"] <- "item"

# unique ID for each participant
df$participant <- paste0(df$Participant, "_", df$Group)

# remove group column
df <- subset(df, select = -c(Group, Participant))

# add language and persona manipulation levels
# (because separate similarity measure for each human compared to each LLM in each condition)

# language
df <- bind_rows(
  df %>% mutate(language = "English"),
  df %>% mutate(language = "Chinese")
)

# persona 
df <- bind_rows(
  df %>% mutate(persona = "China"),
  df %>% mutate(persona = "USA")
)
## LLM ratings
llm <- read_csv("llm_mfq_responses.csv",
                col_select = c("LLM", "language", "persona", "item", "llm_response"))

# merge human responses with LLM responses
df <- left_join(df, llm)

# z-score
df <- df %>%
  group_by(participant) %>%
  mutate(
    human_z = as.numeric(scale(human_response))
  ) %>%
  ungroup() %>%
  group_by(LLM, language) %>%
  mutate(
    llm_z = as.numeric(scale(llm_response))
  ) %>%
  ungroup()

# remove straight liners
df <- filter(df, !is.na(human_z))

```

```{r echo = F}

# ensure vectors are ordered the same for each participant, LLM
df <- arrange(df, participant, LLM, language, persona, item)

df <- df %>%
  group_by(participant, LLM, language, persona) %>%
  summarise(
    cosine = as.numeric(cosine(llm_z, human_z))[1],
    human_nation = ifelse(str_sub(first(participant), -3, -1) == "ina", "China", "USA"),
    .groups = 'drop'
  ) %>%
  ungroup()
  
write_csv(df, "mfq_cosine_rq2.csv")

```

# Cosine similarity as a function of congruence with participant nationality

```{r include = F}

info <- read_csv("llm_info.csv")

df <- left_join(df, info)

```

## Descriptive stats

```{r echo = F}

df %>%
  group_by(llm_name, human_nation, language, persona) %>%
  summarise(
    Mean = mean(cosine),
    SD = sd(cosine)
  ) %>%
  rename(
    LLM = llm_name,
    `Participant nationality` = human_nation,
    Language = language,
    Persona = persona
  ) %>%
  print(n = Inf)

```

### LLMs by country of origin

```{r echo = F}

df %>%
  group_by(llm_nation, human_nation, language, persona) %>%
  summarise(
    Mean = mean(cosine),
    SD = sd(cosine)
  ) %>%
  rename(
    `LLM country of origin` = llm_nation,
    `Participant nationality` = human_nation,
    Language = language,
    Persona = persona
  ) %>%
  print(n = Inf)

```

## Linear regression

#### (Chinese_ppt, Chinese_origin, Chinese_lang, Chinese_persona: China = 0.5, USA = -0.5)

## Mixed effects

```{r echo = F}

df$Chinese_ppt <- ifelse(df$human_nation == "China", 0.5, -0.5)
df$Chinese_ppt <- df$Chinese_ppt - mean(df$Chinese_ppt)

df$Chinese_origin <- ifelse(df$llm_nation == "China", 0.5, -0.5)
df$Chinese_origin <- df$Chinese_origin - mean(df$Chinese_origin)

df$Chinese_lang <- ifelse(df$language == "Chinese", 0.5, -0.5)
df$Chinese_lang <- df$Chinese_lang - mean(df$Chinese_lang)

df$Chinese_persona <- ifelse(df$persona == "China", 0.5, -0.5)
df$Chinese_persona <- df$Chinese_persona - mean(df$Chinese_persona)

summary(lmer(
  cosine ~ 
    Chinese_ppt * Chinese_origin +
    Chinese_ppt * Chinese_lang +
    Chinese_ppt * Chinese_persona + 
    (Chinese_ppt + 1 | LLM) + 
    (Chinese_origin + 1 | participant),
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)), 
  df))

```

## Fixed effects only 

```{r echo = F}

summary(lm(
  cosine ~ 
    Chinese_ppt * Chinese_origin +
    Chinese_ppt * Chinese_lang +
    Chinese_ppt * Chinese_persona, 
  df
))

```
