---
title: "World Values Survey, supplement 2"
output: html_document
---

```{r include = F}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
options(width = 200)

library(tidyverse)
library(ggpubr)
library(lsa)
library(purrr)
library(lmerTest)

```

# Research Question 3, with persona manipulation

```{r include = F}

# load human data

us <- read_delim("human_wvs_usa.csv", delim = ";")
ch <- read_delim("human_wvs_china.csv", delim = ";")

# filter for American (exclude 46) / Chinese (3) nationals
us <- filter(us, B_COUNTRY_ALPHA == "USA", Q254 != 5)
ch <- filter(ch, B_COUNTRY_ALPHA == "CHN", Q254 != 5)

# filter for the 19 ethical values and norms questions
us <- us %>%
  dplyr::select(matches("^Q(17[7-9]|18[0-9]|19[0-5])$")) %>%
  `row.names<-`(NULL)
ch <- ch %>%
  dplyr::select(matches("^Q(17[7-9]|18[0-9]|19[0-5])$")) %>%
  `row.names<-`(NULL)

# valid responses only (1-10)
us <- us %>% 
  mutate(across(everything(), ~ ifelse(. >= 1 & . <= 10, ., NA)))
ch <- ch %>% 
  mutate(across(everything(), ~ ifelse(. >= 1 & . <= 10, ., NA)))

us <- drop_na(us)
ch <- drop_na(ch)

# participant ID
us$participant <- paste0(1:nrow(us), "_USA")
ch$participant <- paste0(1:nrow(ch), "_China")

# one item per row
us <- pivot_longer(us, cols = -c("participant"), names_to = "item", values_to = "human_response")
ch <- pivot_longer(ch, cols = -c("participant"), names_to = "item", values_to = "human_response")

# bind
df <- rbind(us, ch)
rm(us, ch)

# renumber items, without "Q" prefix
df$item <- as.numeric(str_sub(df$item, 2, length(df$item)))


# add language and persona manipulation levels
# (because separate similarity measure for each human compared to each LLM in each condition)

# language
df <- bind_rows(
  df %>% mutate(language = "English"),
  df %>% mutate(language = "Chinese")
)

# persona 
df <- bind_rows(
  df %>% mutate(persona = "China"),
  df %>% mutate(persona = "USA")
)

colnames(df) <- c("participant", "item", "human_response", "language", "persona")


# LLM ratings
# (keeping all LLMs with valid responses when assigned persona)
llm <- read_csv("llm_wvs_persona_responses.csv",
                col_select = c("LLM", "language", "persona", "item", "llm_response"))

# merge human responses with LLM responses
df <- left_join(df, llm)

info <- read_csv("llm_info.csv")

df <- left_join(df, info)

```

```{r include = F}

# initialize output
output = data.frame()

# z-score with/out each dimension
for (i in c(unique(df$item), "none")) {
  
  temp <- filter(df, item != i) %>%
    group_by(participant) %>%
    mutate(
      human_z = as.numeric(scale(human_response))
    ) %>%
    ungroup() %>%
    group_by(LLM, language) %>%
    mutate(
      llm_z = as.numeric(scale(llm_response))
    ) %>%
    ungroup()
  
  # remove straight liners
  temp <- filter(temp, !is.na(human_z))
  temp <- distinct(temp, LLM, participant, item, .keep_all = T)
  
  # ensure vectors are ordered the same for each participant, LLM
  temp <- arrange(temp, participant, LLM, language, item)
  
  temp <- temp %>%
    group_by(participant, LLM, language) %>%
    summarise(
      cosine = as.numeric(cosine(llm_z, human_z))[1],
      human_nation = ifelse(str_sub(first(participant), -3, -1) == "ina", "China", "USA"),
      .groups = 'drop'
    ) %>%
    ungroup()
  
  temp$item <- i
  
  output <- rbind(output, temp)
   
}

write_csv(output, "wvs_cosine_rq3_with_persona.csv")

```

# Similarity to human participants when removing each question

```{r include = F}

info <- read_csv("llm_info.csv")

df <- left_join(output, info)

# sum coding  
df$Chinese_ppt <- ifelse(df$human_nation == "China", 0.5, -0.5)
df$Chinese_ppt <- df$Chinese_ppt - mean(df$Chinese_ppt)

df$China_origin <- ifelse(df$llm_nation == "China", 0.5, -0.5)
df$China_origin <- df$China_origin - mean(df$China_origin)

diff <- filter(df, item == "none")[,c(
  "cosine", "participant", "LLM", "language", "human_nation"
)]

colnames(diff)[1] <- "baseline"

diff <- left_join(df, diff)

diff$cos_diff <- diff$cosine - diff$baseline

```

## Descriptive stats

### Change in cosine similarity when removing each question

```{r echo = F}

filter(diff, item != "none") %>%
  group_by(item, llm_nation, human_nation) %>%
  summarise(
    Mean = mean(cos_diff),
    SD = sd(cos_diff)
  ) %>%
  rename(
    `LLM country of origin` = llm_nation,
    `Participant nationality` = human_nation,
    `Question` = item
  ) %>%
  print(n = Inf)

```

## Linear regression

#### (Chinese_ppt: from China = 0.5, from USA = -0.5)

## Mixed effects

```{r echo = F}

df$item <- relevel(factor(df$item), ref = "none")

summary(lmer(
  cosine ~ 
    Chinese_ppt * China_origin * item +
    (1 | LLM) + (1 | participant),
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)), 
  df))

```

## Fixed effects only

```{r echo = F}

summary(lm(cosine ~ Chinese_ppt * China_origin * item, df))

```
