---
title: "World Values Survey, Research Question 2"
output: html_document
---

```{r include = F}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
options(width = 200)

library(tidyverse)
library(ggpubr)
library(lsa)
library(purrr)
library(gamlss)
library(lmerTest)

```

```{r include = F}

# load human data

us <- read_delim("human_wvs_usa.csv", delim = ";")
ch <- read_delim("human_wvs_china.csv", delim = ";")

# filter for American (exclude 46) / Chinese (3) nationals
us <- filter(us, B_COUNTRY_ALPHA == "USA", Q254 != 5)
ch <- filter(ch, B_COUNTRY_ALPHA == "CHN", Q254 != 5)

# filter for the 19 ethical values and norms questions
us <- us %>%
  dplyr::select(matches("^Q(17[7-9]|18[0-9]|19[0-5])$")) %>%
  `row.names<-`(NULL)
ch <- ch %>%
  dplyr::select(matches("^Q(17[7-9]|18[0-9]|19[0-5])$")) %>%
  `row.names<-`(NULL)

# valid responses only (1-10)
us <- us %>% 
  mutate(across(everything(), ~ ifelse(. >= 1 & . <= 10, ., NA)))
ch <- ch %>% 
  mutate(across(everything(), ~ ifelse(. >= 1 & . <= 10, ., NA)))

us <- drop_na(us)
ch <- drop_na(ch)

# participant ID
us$participant <- paste0(1:nrow(us), "_USA")
ch$participant <- paste0(1:nrow(ch), "_China")

# one item per row
us <- pivot_longer(us, cols = -c("participant"), names_to = "item", values_to = "human_response")
ch <- pivot_longer(ch, cols = -c("participant"), names_to = "item", values_to = "human_response")

# bind
df <- rbind(us, ch)
rm(us, ch)

# renumber items, without "Q" prefix
df$item <- as.numeric(str_sub(df$item, 2, length(df$item)))

# add language and persona manipulation levels
# (because separate similarity measure for each human compared to each LLM in each condition)

# language
df <- bind_rows(
  df %>% mutate(language = "English"),
  df %>% mutate(language = "Chinese")
)

# persona 
df <- bind_rows(
  df %>% mutate(persona = "China"),
  df %>% mutate(persona = "USA")
)

# LLM ratings
# (keeping all LLMs with valid responses when assigned persona)
llm <- read_csv("llm_wvs_persona_responses.csv",
                col_select = c("LLM", "language", "persona", "item", "llm_response"))

# merge human responses with LLM responses
df <- left_join(df, llm)

# z-score
df <- df %>%
  group_by(participant) %>%
  mutate(
    human_z = as.numeric(scale(human_response))
  ) %>%
  ungroup() %>%
  group_by(LLM, language, persona) %>%
  mutate(
    llm_z = as.numeric(scale(llm_response))
  ) %>%
  ungroup()

# remove straight liners
df <- filter(df, !is.na(human_z))

```

```{r echo = F}

# ensure vectors are ordered the same for each participant, LLM
df <- arrange(df, participant, LLM, language, persona, item)

df <- df %>%
  group_by(participant, LLM, language, persona) %>%
  summarise(
    cosine = as.numeric(cosine(llm_z, human_z))[1],
    human_nation = ifelse(str_sub(first(participant), -3, -1) == "ina", "China", "USA"),
    .groups = 'drop'
  ) %>%
  ungroup()
  
write_csv(df, "wvs_cosine_rq2.csv")

```

# Cosine similarity as a function of congruence with participant nationality

```{r include = F}

info <- read_csv("llm_info.csv")

df <- left_join(df, info)

```

## Descriptive stats

```{r echo = F}

df %>%
  group_by(llm_name, human_nation, language, persona) %>%
  summarise(
    Mean = mean(cosine),
    SD = sd(cosine)
  ) %>%
  rename(
    LLM = llm_name,
    `Participant nationality` = human_nation,
    Language = language,
    Persona = persona
  ) %>%
  print(n = Inf)

```

### LLMs by country of origin

```{r echo = F}

df %>%
  group_by(llm_nation, human_nation, language, persona) %>%
  summarise(
    Mean = mean(cosine),
    SD = sd(cosine)
  ) %>%
  rename(
    `LLM country of origin` = llm_nation,
    `Participant nationality` = human_nation,
    Language = language,
    Persona = persona
  ) %>%
  print(n = Inf)

```

## Linear regression

#### (Chinese_ppt, Chinese_origin, Chinese_lang, Chinese_persona: China = 0.5, USA = -0.5)

### Mixed effects

```{r echo = F}

df$Chinese_ppt <- ifelse(df$human_nation == "China", 0.5, -0.5)
df$Chinese_ppt <- df$Chinese_ppt - mean(df$Chinese_ppt)

df$Chinese_origin <- ifelse(df$llm_nation == "China", 0.5, -0.5)
df$Chinese_origin <- df$Chinese_origin - mean(df$Chinese_origin, na.rm = T)

df$Chinese_lang <- ifelse(df$language == "Chinese", 0.5, -0.5)
df$Chinese_lang <- df$Chinese_lang - mean(df$Chinese_lang)

df$Chinese_persona <- ifelse(df$persona == "China", 0.5, -0.5)
df$Chinese_persona <- df$Chinese_persona - mean(df$Chinese_persona, na.rm = T)

summary(lmer(
  cosine ~ 
    Chinese_ppt * Chinese_origin +
    Chinese_ppt * Chinese_lang +
    Chinese_ppt * Chinese_persona + 
    (Chinese_ppt + 1 | LLM) + 
    (Chinese_origin + 1 | participant),
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)), 
  df))

```

### Fixed effects only

```{r echo = F}

summary(lm(
  cosine ~ 
    Chinese_ppt * Chinese_origin +
    Chinese_ppt * Chinese_lang +
    Chinese_ppt * Chinese_persona,
  df
  ))

```